AWSTemplateFormatVersion: '2010-09-09'
Description: Resume AI CI/CD Infrastructure

Resources:
  ResumeSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
      WebsiteConfiguration:
        IndexDocument: index.html

  ResumeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResumeSiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${ResumeSiteBucket.Arn}/*"

  DeploymentTrackingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DeploymentTracking
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: commit_sha
          AttributeType: S
      KeySchema:
        - AttributeName: commit_sha
          KeyType: HASH

  ResumeAnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ResumeAnalytics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: resume_id
          AttributeType: S
      KeySchema:
        - AttributeName: resume_id
          KeyType: HASH

Outputs:
  BucketName:
    Value: !Ref ResumeSiteBucket
